#! /bin/bash
# ivr : iterate vulkan repos
# Execute a command in each of the listed Vulkan GitHub repos.
# http://mew.cx/

GH="/home/mikew/gits/github.com"

for i in \
    KhronosGroup/glslang \
    KhronosGroup/Vulkan-Headers \
    KhronosGroup/Vulkan-Loader \
    KhronosGroup/Vulkan-Tools \
    KhronosGroup/Vulkan-ValidationLayers \
    LunarG/VulkanSamples \
    LunarG/VulkanTools
do
    cd "$GH/$i"
    echo -e "\n{ \"$i\""
    eval "$@"
    echo -e "} \$?=$?\n"
done

# vim: set sw=4 ts=8 et ic ai:
